### ISSUE TITLE
Undefined index: host 

### ISSUE THREAD

**Issue by pacificnm** [Yuav/MogileFS-PHP-Model#3]
Your config set up is throwing an error
yuav/mogilefs/src/MogileFS/File/Mapper/Adapter/Tracker.php
Line 355

The foreach loop never sets any of the config items.
`
foreach ($options['tracker'] as $host) {
			$parts = parse_url($host);
			if (!isset($parts['port'])) {
				$parts['port'] = 7001;
			}

			$errno = null;
			$errstr = null;
			$requestTimeout = isset($options['request_timeout']) ? $options['request_timeout'] : null;
			$this->_socket = fsockopen($parts['host'], $parts['port'], $errno, $errstr, $requestTimeout);
			if ($this->_socket) {
				break;
			}
		}
`

**Comment by Yuav** [comment]
Thanks for patch!

**Comment by pacificnm** [comment]
Your welcome thanks for the library has worked great so far.
